name: rebeat_backend_server
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  angel_framework: ^2.0.0
  http: any
  googleapis: 0.54.0
  googleapis_auth: 0.2.11+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
